
services:
  backend:
    image: tarmairon24/frontend:1.2
    container_name: backend
    restart: always
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: its
      DB_NAME: api
    ports:
      - "3000:3000"
    networks:
      - app-network

  frontend:
    image: tarmairon24/frontend:1.2
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    networks:
      - app-network

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: its
      POSTGRES_DB: api
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    external: true

volumes:
  pgdata:

