services:
  frontend: 
    image: tarmairon24/frontend:latest
    container_name: frontend
    restart: always
    ports:
      - "5173:5173"
    networks:
      - app-network

networks:
  app-network:
    external: true